#!/bin/bash

# Directories
PREF='/home/dvulakh/recgen'
INPF='/home/dvulakh/lustrefs/data'

# Push lots of small jobs
for F in $INPF/*T4-A4*; do
    nohup sbatch $PREF/batches/quad-batch $F &
done
wait
