#!/bin/bash

######################################################################
# Given a tree-diff data file and generation count as command-line
# arguments, produces graphs of the distributions of block
# reconstruction accuracies within each generation
#
# Run from project directory with analysis/graph_blocks
# (do not run inside analysis)
######################################################################

TMP='.tmp-graph-blocks.dat'
DAT='tree-diff.dat'; if [ ! -z "$1" ]; then DAT=$1; fi
GEN=10; if [ ! -z "$2" ]; then GEN=$2; fi
OUT='rec-gen-graphs/blocks-'; if [ ! -z "$3" ]; then OUT=$3; fi
for (( g=1; g<=$GEN; g++ )); do
	[[ $OUT =~ rec-gen-graphs/.* ]] && mkdir -p './rec-gen-graphs'
	sed -n -E 's|^.*Comparing.*grade\s'"$g"'.*\(([0-9]+)%/.*$|\1|p' $DAT > $TMP
	if [ -s $TMP ]; then
		gnuplot -e "fin='$TMP'; fout='$OUT$g.png'; titin='Block recovery distribution, gen $g'" analysis/blocks_distribution.plt;
	fi
done
rm $TMP
